version: 2
updates:
  - package-ecosystem: docker
    directory: "/.devcontainer"
    schedule:
      interval: "weekly"
    labels:
      - "Type: Maintenance"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "Type: Maintenance"
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "Type: Maintenance"
    groups:
      fiber:
        patterns:
          - "github.com/gofiber/*"
